Fix ``pip install ldap3-orm`` fails with unrecognized option.
The install command was derived from distutils before which does
not provide the option ``--single-version-externally-managed``
This resulted in the following error::

    error: option --single-version-externally-managed not recognized

Importing the base install class from setuptools resolves this issue.

Change-Id: Ic75944cc14de7de25bfa9a393d22b9d6aba3ef6c
Reviewed-on: https://code.bsm-felder.de/review/246
Reviewed-by: Christian Felder <webmaster@bsm-felder.de>